/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { MedicineInventoryEntryFromJSON, MedicineInventoryEntryToJSON, } from '../models';
/**
 *
 */
export class MedicineInventoryApi extends runtime.BaseAPI {
    /**
     * Use this method to delete the specific entry from the medicine inventory.
     * Deletes specific entry
     */
    async deleteMedicineInventoryEntryRaw(requestParameters, initOverrides) {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId', 'Required parameter requestParameters.ambulanceId was null or undefined when calling deleteMedicineInventoryEntry.');
        }
        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId', 'Required parameter requestParameters.entryId was null or undefined when calling deleteMedicineInventoryEntry.');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/medicine-inventory/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * Use this method to delete the specific entry from the medicine inventory.
     * Deletes specific entry
     */
    async deleteMedicineInventoryEntry(requestParameters, initOverrides) {
        await this.deleteMedicineInventoryEntryRaw(requestParameters, initOverrides);
    }
    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * Provides the ambulance medicine inventory
     */
    async getMedicineInventoryEntriesRaw(requestParameters, initOverrides) {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId', 'Required parameter requestParameters.ambulanceId was null or undefined when calling getMedicineInventoryEntries.');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/medicine-inventory/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicineInventoryEntryFromJSON));
    }
    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * Provides the ambulance medicine inventory
     */
    async getMedicineInventoryEntries(requestParameters, initOverrides) {
        const response = await this.getMedicineInventoryEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine inventory.
     * Provides details about ambulance medicine inventory entry
     */
    async getMedicineInventoryEntryRaw(requestParameters, initOverrides) {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId', 'Required parameter requestParameters.ambulanceId was null or undefined when calling getMedicineInventoryEntry.');
        }
        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId', 'Required parameter requestParameters.entryId was null or undefined when calling getMedicineInventoryEntry.');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/medicine-inventory/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineInventoryEntryFromJSON(jsonValue));
    }
    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine inventory.
     * Provides details about ambulance medicine inventory entry
     */
    async getMedicineInventoryEntry(requestParameters, initOverrides) {
        const response = await this.getMedicineInventoryEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Use this method to update content of the medicine inventory entry.
     * Updates specific entry
     */
    async updateMedicineInventoryEntryRaw(requestParameters, initOverrides) {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId', 'Required parameter requestParameters.ambulanceId was null or undefined when calling updateMedicineInventoryEntry.');
        }
        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId', 'Required parameter requestParameters.entryId was null or undefined when calling updateMedicineInventoryEntry.');
        }
        if (requestParameters.medicineInventoryEntry === null || requestParameters.medicineInventoryEntry === undefined) {
            throw new runtime.RequiredError('medicineInventoryEntry', 'Required parameter requestParameters.medicineInventoryEntry was null or undefined when calling updateMedicineInventoryEntry.');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/medicine-inventory/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MedicineInventoryEntryToJSON(requestParameters.medicineInventoryEntry),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineInventoryEntryFromJSON(jsonValue));
    }
    /**
     * Use this method to update content of the medicine inventory entry.
     * Updates specific entry
     */
    async updateMedicineInventoryEntry(requestParameters, initOverrides) {
        const response = await this.updateMedicineInventoryEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
