/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MedicineOrderEntry,
} from '../models';
import {
    MedicineOrderEntryFromJSON,
    MedicineOrderEntryToJSON,
} from '../models';

export interface CreateMedicineOrderEntryRequest {
    ambulanceId: string;
    medicineOrderEntry: MedicineOrderEntry;
}

export interface DeleteMedicineOrderEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface GetMedicineOrderEntriesRequest {
    ambulanceId: string;
}

export interface GetMedicineOrderEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface UpdateMedicineOrderEntryRequest {
    ambulanceId: string;
    entryId: string;
    medicineOrderEntry: MedicineOrderEntry;
}

/**
 * MedicineOrderApi - interface
 * 
 * @export
 * @interface MedicineOrderApiInterface
 */
export interface MedicineOrderApiInterface {
    /**
     * Use this method to store new entry into the medicine order list.
     * @summary Saves new entry into medicine order
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {MedicineOrderEntry} medicineOrderEntry Medicine order entry to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineOrderApiInterface
     */
    createMedicineOrderEntryRaw(requestParameters: CreateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>>;

    /**
     * Use this method to store new entry into the medicine order list.
     * Saves new entry into medicine order
     */
    createMedicineOrderEntry(requestParameters: CreateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry>;

    /**
     * Use this method to delete the specific entry from the medicine orders.
     * @summary Deletes specific entry
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {string} entryId pass the id of the particular entry in the medicine inventory
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineOrderApiInterface
     */
    deleteMedicineOrderEntryRaw(requestParameters: DeleteMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific entry from the medicine orders.
     * Deletes specific entry
     */
    deleteMedicineOrderEntry(requestParameters: DeleteMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using ambulanceId you get list of orders for the given ambulance
     * @summary Provides orders of the ambulance
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineOrderApiInterface
     */
    getMedicineOrderEntriesRaw(requestParameters: GetMedicineOrderEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicineOrderEntry>>>;

    /**
     * By using ambulanceId you get list of orders for the given ambulance
     * Provides orders of the ambulance
     */
    getMedicineOrderEntries(requestParameters: GetMedicineOrderEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicineOrderEntry>>;

    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine order.
     * @summary Provides details about ambulance medicine order entry
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {string} entryId pass the id of the particular entry in the medicine order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineOrderApiInterface
     */
    getMedicineOrderEntryRaw(requestParameters: GetMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>>;

    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine order.
     * Provides details about ambulance medicine order entry
     */
    getMedicineOrderEntry(requestParameters: GetMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry>;

    /**
     * Use this method to update content of the medicine order entry.
     * @summary Updates specific entry
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {string} entryId pass the id of the particular entry in the medicine order
     * @param {MedicineOrderEntry} medicineOrderEntry Medicine order entry to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineOrderApiInterface
     */
    updateMedicineOrderEntryRaw(requestParameters: UpdateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>>;

    /**
     * Use this method to update content of the medicine order entry.
     * Updates specific entry
     */
    updateMedicineOrderEntry(requestParameters: UpdateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry>;

}

/**
 * 
 */
export class MedicineOrderApi extends runtime.BaseAPI implements MedicineOrderApiInterface {

    /**
     * Use this method to store new entry into the medicine order list.
     * Saves new entry into medicine order
     */
    async createMedicineOrderEntryRaw(requestParameters: CreateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling createMedicineOrderEntry.');
        }

        if (requestParameters.medicineOrderEntry === null || requestParameters.medicineOrderEntry === undefined) {
            throw new runtime.RequiredError('medicineOrderEntry','Required parameter requestParameters.medicineOrderEntry was null or undefined when calling createMedicineOrderEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/medicine-order/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MedicineOrderEntryToJSON(requestParameters.medicineOrderEntry),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineOrderEntryFromJSON(jsonValue));
    }

    /**
     * Use this method to store new entry into the medicine order list.
     * Saves new entry into medicine order
     */
    async createMedicineOrderEntry(requestParameters: CreateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry> {
        const response = await this.createMedicineOrderEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific entry from the medicine orders.
     * Deletes specific entry
     */
    async deleteMedicineOrderEntryRaw(requestParameters: DeleteMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deleteMedicineOrderEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling deleteMedicineOrderEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/medicine-order/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific entry from the medicine orders.
     * Deletes specific entry
     */
    async deleteMedicineOrderEntry(requestParameters: DeleteMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMedicineOrderEntryRaw(requestParameters, initOverrides);
    }

    /**
     * By using ambulanceId you get list of orders for the given ambulance
     * Provides orders of the ambulance
     */
    async getMedicineOrderEntriesRaw(requestParameters: GetMedicineOrderEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicineOrderEntry>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getMedicineOrderEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/medicine-order/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicineOrderEntryFromJSON));
    }

    /**
     * By using ambulanceId you get list of orders for the given ambulance
     * Provides orders of the ambulance
     */
    async getMedicineOrderEntries(requestParameters: GetMedicineOrderEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicineOrderEntry>> {
        const response = await this.getMedicineOrderEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine order.
     * Provides details about ambulance medicine order entry
     */
    async getMedicineOrderEntryRaw(requestParameters: GetMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getMedicineOrderEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling getMedicineOrderEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/medicine-order/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineOrderEntryFromJSON(jsonValue));
    }

    /**
     * By using ambulanceId and entryId you can details of particular entry ambulance medicine order.
     * Provides details about ambulance medicine order entry
     */
    async getMedicineOrderEntry(requestParameters: GetMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry> {
        const response = await this.getMedicineOrderEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update content of the medicine order entry.
     * Updates specific entry
     */
    async updateMedicineOrderEntryRaw(requestParameters: UpdateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicineOrderEntry>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updateMedicineOrderEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling updateMedicineOrderEntry.');
        }

        if (requestParameters.medicineOrderEntry === null || requestParameters.medicineOrderEntry === undefined) {
            throw new runtime.RequiredError('medicineOrderEntry','Required parameter requestParameters.medicineOrderEntry was null or undefined when calling updateMedicineOrderEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/medicine-order/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MedicineOrderEntryToJSON(requestParameters.medicineOrderEntry),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineOrderEntryFromJSON(jsonValue));
    }

    /**
     * Use this method to update content of the medicine order entry.
     * Updates specific entry
     */
    async updateMedicineOrderEntry(requestParameters: UpdateMedicineOrderEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicineOrderEntry> {
        const response = await this.updateMedicineOrderEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
