/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MedicineInventoryEntry,
} from '../models';
import {
    MedicineInventoryEntryFromJSON,
    MedicineInventoryEntryToJSON,
} from '../models';

export interface GetMedicineInventoryEntriesRequest {
    ambulanceId: string;
}

/**
 * MedicineInventoryApi - interface
 * 
 * @export
 * @interface MedicineInventoryApiInterface
 */
export interface MedicineInventoryApiInterface {
    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * @summary Provides the ambulance medicine inventory
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicineInventoryApiInterface
     */
    getMedicineInventoryEntriesRaw(requestParameters: GetMedicineInventoryEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicineInventoryEntry>>>;

    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * Provides the ambulance medicine inventory
     */
    getMedicineInventoryEntries(requestParameters: GetMedicineInventoryEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicineInventoryEntry>>;

}

/**
 * 
 */
export class MedicineInventoryApi extends runtime.BaseAPI implements MedicineInventoryApiInterface {

    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * Provides the ambulance medicine inventory
     */
    async getMedicineInventoryEntriesRaw(requestParameters: GetMedicineInventoryEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicineInventoryEntry>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getMedicineInventoryEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/medicine-inventory/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicineInventoryEntryFromJSON));
    }

    /**
     * By using ambulanceId you get list of entries in ambulance medicine inventory
     * Provides the ambulance medicine inventory
     */
    async getMedicineInventoryEntries(requestParameters: GetMedicineInventoryEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicineInventoryEntry>> {
        const response = await this.getMedicineInventoryEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
