/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Status,
} from '../models';
import {
    StatusFromJSON,
    StatusToJSON,
} from '../models';

/**
 * OrderStatusesApi - interface
 * 
 * @export
 * @interface OrderStatusesApiInterface
 */
export interface OrderStatusesApiInterface {
    /**
     * Get list of predefined order statuses
     * @summary Provides the list of valid statuses for the order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderStatusesApiInterface
     */
    getStatusesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Status>>>;

    /**
     * Get list of predefined order statuses
     * Provides the list of valid statuses for the order
     */
    getStatuses(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Status>>;

}

/**
 * 
 */
export class OrderStatusesApi extends runtime.BaseAPI implements OrderStatusesApiInterface {

    /**
     * Get list of predefined order statuses
     * Provides the list of valid statuses for the order
     */
    async getStatusesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Status>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/medicine-order/statuses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StatusFromJSON));
    }

    /**
     * Get list of predefined order statuses
     * Provides the list of valid statuses for the order
     */
    async getStatuses(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Status>> {
        const response = await this.getStatusesRaw(initOverrides);
        return await response.value();
    }

}
