/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MedicineInventoryEntry } from './MedicineInventoryEntry';
import {
    MedicineInventoryEntryFromJSON,
    MedicineInventoryEntryFromJSONTyped,
    MedicineInventoryEntryToJSON,
} from './MedicineInventoryEntry';
import type { MedicineOrderEntry } from './MedicineOrderEntry';
import {
    MedicineOrderEntryFromJSON,
    MedicineOrderEntryFromJSONTyped,
    MedicineOrderEntryToJSON,
} from './MedicineOrderEntry';

/**
 * 
 * @export
 * @interface Ambulance
 */
export interface Ambulance {
    /**
     * Unique identifier of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    id: string;
    /**
     * Human readable display name of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Ambulance
     */
    roomNumber: string;
    /**
     * 
     * @type {Array<MedicineInventoryEntry>}
     * @memberof Ambulance
     */
    medicineInventory?: Array<MedicineInventoryEntry>;
    /**
     * 
     * @type {Array<MedicineOrderEntry>}
     * @memberof Ambulance
     */
    medicineOrders?: Array<MedicineOrderEntry>;
}

/**
 * Check if a given object implements the Ambulance interface.
 */
export function instanceOfAmbulance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "roomNumber" in value;

    return isInstance;
}

export function AmbulanceFromJSON(json: any): Ambulance {
    return AmbulanceFromJSONTyped(json, false);
}

export function AmbulanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ambulance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'roomNumber': json['roomNumber'],
        'medicineInventory': !exists(json, 'medicineInventory') ? undefined : ((json['medicineInventory'] as Array<any>).map(MedicineInventoryEntryFromJSON)),
        'medicineOrders': !exists(json, 'medicineOrders') ? undefined : ((json['medicineOrders'] as Array<any>).map(MedicineOrderEntryFromJSON)),
    };
}

export function AmbulanceToJSON(value?: Ambulance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'roomNumber': value.roomNumber,
        'medicineInventory': value.medicineInventory === undefined ? undefined : ((value.medicineInventory as Array<any>).map(MedicineInventoryEntryToJSON)),
        'medicineOrders': value.medicineOrders === undefined ? undefined : ((value.medicineOrders as Array<any>).map(MedicineOrderEntryToJSON)),
    };
}

