/* tslint:disable */
/* eslint-disable */
/**
 * Medicine Inventory API
 * Medicine inventory management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the MedicineInventoryEntry interface.
 */
export function instanceOfMedicineInventoryEntry(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "medicineId" in value;
    isInstance = isInstance && "count" in value;
    return isInstance;
}
export function MedicineInventoryEntryFromJSON(json) {
    return MedicineInventoryEntryFromJSONTyped(json, false);
}
export function MedicineInventoryEntryFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'medicineId': json['medicineId'],
        'count': json['count'],
    };
}
export function MedicineInventoryEntryToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'medicineId': value.medicineId,
        'count': value.count,
    };
}
