/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EeMedicineInventory {
    }
}
declare global {
    interface HTMLEeMedicineInventoryElement extends Components.EeMedicineInventory, HTMLStencilElement {
    }
    var HTMLEeMedicineInventoryElement: {
        prototype: HTMLEeMedicineInventoryElement;
        new (): HTMLEeMedicineInventoryElement;
    };
    interface HTMLElementTagNameMap {
        "ee-medicine-inventory": HTMLEeMedicineInventoryElement;
    }
}
declare namespace LocalJSX {
    interface EeMedicineInventory {
    }
    interface IntrinsicElements {
        "ee-medicine-inventory": EeMedicineInventory;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ee-medicine-inventory": LocalJSX.EeMedicineInventory & JSXBase.HTMLAttributes<HTMLEeMedicineInventoryElement>;
        }
    }
}
